const TOEIC_QUESTIONS = [
  {
    id: "q1",
    question:
      "An architect with over 20 years of experience in designing and developing spaces was the ------ for the seminar.",
    options: ["instruct", "instructor", "instructive", "instruction"],
    answer: "B",
    explanation: {
      vi: "Chỗ trống đứng sau mạo từ 'the', cần một danh từ. Dựa vào ngữ cảnh, vị trí này cần một danh từ chỉ người. 'Instructor' (người hướng dẫn, giảng viên) là danh từ chỉ người duy nhất phù hợp. Dịch: Một kiến trúc sư với hơn 20 năm kinh nghiệm thiết kế và phát triển không gian là người hướng dẫn cho buổi hội thảo.",
      en: "The blank follows the article 'the', requiring a noun. Based on the context, a noun for a person is needed. 'Instructor' is the only suitable noun for a person. Translation: An architect with over 20 years of experience in designing and developing spaces was the instructor for the seminar.",
    },
    grammar_tags: ["word_form", "noun"],
    vocab_tags: ["jobs", "education"],
    difficulty: 2,
    distractor_notes: {
      A: "Đây là một động từ (hướng dẫn).",
      C: "Đây là một tính từ (cung cấp thông tin hữu ích).",
      D: "Đây là một danh từ chỉ vật (sự hướng dẫn).",
    },
    hint: "Look for a noun that refers to a person's role.",
  },
  {
    id: "q2",
    question:
      "Unless Express Telecom is explicitly told to cancel a subscription, it ------ to charge users the regular monthly fee.",
    options: [
      "continues",
      "will continue",
      "would continue",
      "would have continued",
    ],
    answer: "B",
    explanation: {
      vi: "Đây là câu điều kiện loại 1 với 'Unless' (trừ khi). Mệnh đề 'unless' dùng thì hiện tại đơn, nên mệnh đề chính sẽ dùng thì tương lai đơn (will + V). Dịch: Trừ khi Express Telecom được yêu cầu hủy đăng ký một cách rõ ràng, họ sẽ tiếp tục tính phí hàng tháng thông thường cho người dùng.",
      en: "This is a Type 1 conditional sentence with 'Unless'. The 'unless' clause uses the simple present tense, so the main clause uses the simple future tense (will + V). Translation: Unless Express Telecom is explicitly told to cancel a subscription, it will continue to charge users the regular monthly fee.",
    },
    grammar_tags: ["conditional", "type_1", "verb_tense"],
    vocab_tags: ["business", "subscription", "policy"],
    difficulty: 3,
    distractor_notes: {
      A: "Sai thì, mệnh đề chính của câu điều kiện loại 1 cần thì tương lai.",
      C: "Sai thì, 'would continue' được dùng trong câu điều kiện loại 2.",
      D: "Sai thì, 'would have continued' được dùng trong câu điều kiện loại 3.",
    },
    hint: "What tense is used in the main clause of a first conditional sentence?",
  },
  {
    id: "q3",
    question:
      "The manager has asked new interns to help ------ plan a marketing campaign for some products.",
    options: ["she", "her", "herself", "hers"],
    answer: "B",
    explanation: {
      vi: "Động từ 'help' cần một tân ngữ theo sau. 'Her' là đại từ tân ngữ. Dịch: Người quản lý đã yêu cầu các thực tập sinh mới giúp cô ấy lên kế hoạch cho một chiến dịch tiếp thị cho một số sản phẩm.",
      en: "The verb 'help' requires an object pronoun to follow. 'Her' is the object pronoun. Translation: The manager has asked new interns to help her plan a marketing campaign for some products.",
    },
    grammar_tags: ["pronoun", "object_pronoun"],
    vocab_tags: ["office", "marketing"],
    difficulty: 1,
    distractor_notes: {
      A: "'She' là đại từ chủ ngữ, không thể đứng sau động từ 'help'.",
      C: "'Herself' là đại từ phản thân, dùng khi chủ ngữ và tân ngữ là một.",
      D: "'Hers' là đại từ sở hữu, thay thế cho 'her + noun'.",
    },
    hint: "Which pronoun form is used after a verb like 'help'?",
  },
  {
    id: "q4",
    question:
      "Từ nào sau đây trong tiếng Anh có nghĩa là 'sự cho phép' hoặc 'sự chấp thuận'?",
    options: ["prohibit", "authorize", "approval", "regulate"],
    answer: "C",
    explanation: {
      vi: "'Approval' là một danh từ có nghĩa là sự chấp thuận, sự cho phép.",
      en: "'Approval' is a noun that means the act of agreeing to or accepting something.",
    },
    grammar_tags: ["vocabulary"],
    vocab_tags: ["permission", "business"],
    difficulty: 2,
    distractor_notes: {
      A: "'Prohibit' là động từ, nghĩa là cấm.",
      B: "'Authorize' là động từ, nghĩa là ủy quyền, cho phép.",
      D: "'Regulate' là động từ, nghĩa là quy định, điều chỉnh.",
    },
    hint: "Bạn đang tìm một danh từ (noun).",
  },
  {
    id: "q5",
    question:
      "The new printer operates more ------ than the previous model did.",
    options: ["quick", "quicker", "quickly", "quickest"],
    answer: "C",
    explanation: {
      vi: "Cần một trạng từ để bổ nghĩa cho động từ 'operates'. 'Quickly' là trạng từ. Cấu trúc so sánh hơn của trạng từ là 'more + adv'. Dịch: Máy in mới hoạt động nhanh hơn so với model trước đó.",
      en: "An adverb is needed to modify the verb 'operates'. 'Quickly' is the adverb. The comparative form for this adverb is 'more + adv'. Translation: The new printer operates more quickly than the previous model did.",
    },
    grammar_tags: ["adverb", "comparative"],
    vocab_tags: ["technology", "office_equipment"],
    difficulty: 3,
    distractor_notes: {
      A: "'Quick' là một tính từ.",
      B: "'Quicker' là dạng so sánh hơn của tính từ.",
      D: "'Quickest' là dạng so sánh nhất của tính từ.",
    },
    hint: "You need a word to describe *how* the printer operates. This requires an adverb.",
  },
  {
    id: "q6",
    question:
      "The tour bus drove ------ several notable sites in Brisbane and made three stops.",
    options: ["past", "out", "in", "up"],
    answer: "A",
    explanation: {
      vi: "Giới từ 'past' có nghĩa là 'đi ngang qua'. Đây là lựa chọn hợp lý nhất về mặt ngữ nghĩa. Dịch: Xe buýt du lịch đã lái xe qua một số địa điểm đáng chú ý ở Brisbane và dừng lại ba lần.",
      en: "The preposition 'past' means 'going by'. It is the most semantically appropriate choice. Translation: The tour bus drove past several notable sites in Brisbane and made three stops.",
    },
    grammar_tags: ["preposition", "preposition_of_place"],
    vocab_tags: ["travel", "tourism"],
    difficulty: 2,
    distractor_notes: {
      B: "'drove out' có nghĩa là lái xe ra khỏi.",
      C: "'drove in' có nghĩa là lái xe vào trong.",
      D: "'drove up' có nghĩa là lái xe đến gần.",
    },
    hint: "Which preposition means 'to go by a place'?",
  },
  {
    id: "q7",
    question:
      "Improvements to the subway system ------ city residents to reduce their reliance on cars in recent years.",
    options: ["allow", "is allowing", "have allowed", "allowed"],
    answer: "C",
    explanation: {
      vi: "Cụm từ 'in recent years' (trong những năm gần đây) là dấu hiệu của thì hiện tại hoàn thành. Chủ ngữ 'improvements' là số nhiều, do đó ta dùng 'have allowed'. Dịch: Những cải tiến đối với hệ thống tàu điện ngầm đã cho phép cư dân thành phố giảm sự phụ thuộc vào ô tô trong những năm gần đây.",
      en: "The phrase 'in recent years' is a signal for the present perfect tense. The subject 'improvements' is plural, so 'have allowed' is the correct form. Translation: Improvements to the subway system have allowed city residents to reduce their reliance on cars in recent years.",
    },
    grammar_tags: ["verb_tense", "present_perfect"],
    vocab_tags: ["transportation", "city_life"],
    difficulty: 3,
    distractor_notes: {
      A: "Thì hiện tại đơn không phù hợp với 'in recent years'.",
      B: "Thì hiện tại tiếp diễn không phù hợp và sai hòa hợp chủ-vị.",
      D: "Thì quá khứ đơn không diễn tả hành động kéo dài đến hiện tại.",
    },
    hint: "The phrase 'in recent years' indicates an action that started in the past and continues to have an effect in the present.",
  },
  {
    id: "q8",
    question:
      "Richard Lucas will give away copies of his new book to visitors ------ attend his photo exhibit.",
    options: ["whose", "which", "when", "who"],
    answer: "D",
    explanation: {
      vi: "Cần một đại từ quan hệ để thay thế cho danh từ chỉ người 'visitors' và làm chủ ngữ cho động từ 'attend'. 'Who' là đại từ quan hệ phù hợp. Dịch: Richard Lucas sẽ tặng các bản sách mới của mình cho những khách tham quan tham dự triển lãm ảnh của ông.",
      en: "A relative pronoun is needed to replace the noun for people ('visitors') and act as the subject for the verb 'attend'. 'Who' is the correct relative pronoun. Translation: Richard Lucas will give away copies of his new book to visitors who attend his photo exhibit.",
    },
    grammar_tags: ["relative_clause", "relative_pronoun"],
    vocab_tags: ["events", "art"],
    difficulty: 2,
    distractor_notes: {
      A: "'Whose' chỉ sự sở hữu.",
      C: "'When' chỉ thời gian.",
      B: "'Which' chỉ vật.",
    },
    hint: "The relative pronoun must refer to 'visitors' (people).",
  },
  {
    id: "q9",
    question:
      "Choosing a major is not easy, ------ students need more consultation with their parents and teachers.",
    options: ["so", "whereas", "or", "even"],
    answer: "A",
    explanation: {
      vi: "Mệnh đề thứ hai là kết quả của mệnh đề thứ nhất. 'So' (vì vậy) là liên từ dùng để chỉ kết quả. Dịch: Chọn chuyên ngành không dễ, vì vậy sinh viên cần thêm sự tư vấn từ cha mẹ và giáo viên.",
      en: "The second clause is a result of the first clause. 'So' is the conjunction used to indicate a result. Translation: Choosing a major is not easy, so students need more consultation with their parents and teachers.",
    },
    grammar_tags: ["conjunction", "coordinating_conjunction"],
    vocab_tags: ["education", "decision_making"],
    difficulty: 2,
    distractor_notes: {
      B: "'Whereas' chỉ sự đối lập.",
      C: "'Or' chỉ sự lựa chọn.",
      D: "'Even' là một trạng từ, không phải liên từ nối hai mệnh đề độc lập.",
    },
    hint: "The relationship between the two clauses is cause and effect.",
  },
  {
    id: "q10",
    question: "Many businesses promote carpooling ------ traffic congestion.",
    options: ["is prevented", "prevent", "to prevent", "prevented"],
    answer: "C",
    explanation: {
      vi: "Để diễn tả mục đích, ta dùng cấu trúc 'to + V-nguyên thể' (to-infinitive). Dịch: Nhiều doanh nghiệp thúc đẩy việc đi chung xe để ngăn chặn tắc nghẽn giao thông.",
      en: "To express purpose, the 'to-infinitive' structure is used. Translation: Many businesses promote carpooling to prevent traffic congestion.",
    },
    grammar_tags: ["verb_form", "infinitive_of_purpose"],
    vocab_tags: ["transportation", "environment"],
    difficulty: 2,
    distractor_notes: {
      A: "Sai cấu trúc, đây là dạng bị động của một mệnh đề.",
      B: "Sai cấu trúc, động từ nguyên thể không 'to' không dùng để chỉ mục đích ở đây.",
      D: "Sai cấu trúc, đây là dạng quá khứ phân từ.",
    },
    hint: "How do you express the purpose or reason for an action?",
  },
  {
    id: "q11",
    question: "What is the English word for 'có thể, khả thi'?",
    options: ["mandatory", "feasible", "obsolete", "abundant"],
    answer: "B",
    explanation: {
      vi: "'Feasible' là một tính từ có nghĩa là có thể thực hiện được, khả thi.",
      en: "'Feasible' is an adjective that means possible to do easily or conveniently.",
    },
    grammar_tags: ["vocabulary"],
    vocab_tags: ["adjective", "planning"],
    difficulty: 4,
    distractor_notes: {
      A: "'Mandatory' có nghĩa là bắt buộc.",
      C: "'Obsolete' có nghĩa là lỗi thời.",
      D: "'Abundant' có nghĩa là dồi dào, phong phú.",
    },
    hint: "This word is often used to describe a plan or a project that can be successfully completed.",
  },
  {
    id: "q12",
    question:
      "The new manager is not only competent ------ also very approachable.",
    options: ["and", "or", "but", "so"],
    answer: "C",
    explanation: {
      vi: "Đây là cấu trúc liên từ tương quan 'not only... but also...' (không những... mà còn...). Dịch: Người quản lý mới không chỉ có năng lực mà còn rất dễ gần.",
      en: "This is the correlative conjunction structure 'not only... but also...'. Translation: The new manager is not only competent but also very approachable.",
    },
    grammar_tags: ["conjunction", "correlative_conjunction"],
    vocab_tags: ["personality", "workplace"],
    difficulty: 2,
    distractor_notes: {
      A: "Sai cấu trúc.",
      B: "Sai cấu trúc.",
      D: "Sai cấu trúc.",
    },
    hint: "What word typically follows 'not only' in a sentence?",
  },
  {
    id: "q13",
    question:
      "The study showed that customers aged 35 to 44 paid with a credit card more ------ than customers in any other age group.",
    options: ["frequently", "frequent", "more frequent", "frequency"],
    answer: "A",
    explanation: {
      vi: "Cần một trạng từ để bổ nghĩa cho động từ 'paid'. 'Frequently' là trạng từ. Cấu trúc so sánh hơn 'more frequently' đã có sẵn 'more', nên chỉ cần chọn trạng từ gốc. Dịch: Nghiên cứu cho thấy khách hàng từ 35 đến 44 tuổi thanh toán bằng thẻ tín dụng thường xuyên hơn khách hàng ở bất kỳ nhóm tuổi nào khác.",
      en: "An adverb is needed to modify the verb 'paid'. 'Frequently' is the adverb. The comparative 'more frequently' already contains 'more', so you just need the base adverb. Translation: The study showed that customers aged 35 to 44 paid with a credit card more frequently than customers in any other age group.",
    },
    grammar_tags: ["word_form", "adverb", "comparative"],
    vocab_tags: ["finance", "research", "demographics"],
    difficulty: 4,
    distractor_notes: {
      B: "'Frequent' là một tính từ.",
      C: "'More frequent' là dạng so sánh hơn của tính từ.",
      D: "'Frequency' là một danh từ.",
    },
    hint: "The word must describe *how* the customers paid. Also, notice the word 'more' is already in the sentence.",
  },
  {
    id: "q14",
    question:
      "No one in the department ------ the new product launch more eagerly than Lee.",
    options: ["awaits", "await", "is awaiting", "are awaiting"],
    answer: "A",
    explanation: {
      vi: "Chủ ngữ là 'No one', là một đại từ bất định số ít, vì vậy động từ phải chia ở dạng số ít. 'Awaits' là dạng đúng. Dịch: Không ai trong phòng ban mong chờ sự kiện ra mắt sản phẩm mới háo hức hơn Lee.",
      en: "The subject is 'No one', which is a singular indefinite pronoun, so the verb must be in the singular form. 'Awaits' is the correct form. Translation: No one in the department awaits the new product launch more eagerly than Lee.",
    },
    grammar_tags: ["subject_verb_agreement", "indefinite_pronoun"],
    vocab_tags: ["marketing", "office"],
    difficulty: 3,
    distractor_notes: {
      B: "Dạng số nhiều, không hợp với chủ ngữ 'No one'.",
      C: "Mặc dù đúng về số ít, thì tiếp diễn không cần thiết ở đây để diễn tả một trạng thái mong chờ chung.",
      D: "Sai cả về số và thì.",
    },
    hint: "The subject 'No one' is singular.",
  },
  {
    id: "q15",
    question:
      "------ the facilitator was knowledgeable, she was not willing to answer our questions.",
    options: ["Because", "Besides", "Although", "Since"],
    answer: "C",
    explanation: {
      vi: "Hai mệnh đề trong câu có ý nghĩa tương phản, đối lập nhau (giỏi nhưng không sẵn lòng trả lời). 'Although' (mặc dù) là liên từ chỉ sự nhượng bộ, phù hợp với ngữ cảnh này. Dịch: Mặc dù người điều phối có kiến thức, cô ấy không sẵn lòng trả lời các câu hỏi của chúng tôi.",
      en: "The two clauses in the sentence have contrasting meanings. 'Although' is a conjunction of concession, which fits this context. Translation: Although the facilitator was knowledgeable, she was not willing to answer our questions.",
    },
    grammar_tags: ["conjunction", "subordinating_conjunction", "concession"],
    vocab_tags: ["meeting", "communication"],
    difficulty: 3,
    distractor_notes: {
      A: "'Because' chỉ nguyên nhân.",
      B: "'Besides' là một giới từ hoặc trạng từ, không phải liên từ phụ thuộc.",
      D: "'Since' chỉ nguyên nhân hoặc mốc thời gian.",
    },
    hint: "The sentence presents a contrast between a positive quality and a negative action.",
  },
  {
    id: "q16",
    question:
      "The director requires all staff members to wear formal business attire on Thursday ------ they have meetings with clients.",
    options: ["that", "where", "when", "which"],
    answer: "C",
    explanation: {
      vi: "Mệnh đề phụ chỉ thời điểm diễn ra hành động ở mệnh đề chính. 'Thursday' là một danh từ chỉ thời gian. Do đó, trạng từ quan hệ 'when' (khi) là lựa chọn chính xác. Dịch: Giám đốc yêu cầu tất cả nhân viên mặc trang phục công sở trang trọng vào thứ Năm khi họ có cuộc họp với khách hàng.",
      en: "The subordinate clause indicates the time when the action in the main clause occurs. 'Thursday' is a noun of time. Therefore, the relative adverb 'when' is the correct choice. Translation: The director requires all staff members to wear formal business attire on Thursday when they have meetings with clients.",
    },
    grammar_tags: ["relative_clause", "relative_adverb"],
    vocab_tags: ["office_policy", "business"],
    difficulty: 3,
    distractor_notes: {
      A: "Không phù hợp.",
      B: "'Where' chỉ nơi chốn.",
      D: "'Which' dùng cho vật.",
    },
    hint: "The clause explains what happens on Thursday. It refers to a time.",
  },
  {
    id: "q17",
    question:
      "To avoid unexpected issues, all procedures ------ in this manual must be implemented.",
    options: ["written", "wrote", "writing", "write"],
    answer: "A",
    explanation: {
      vi: "Đây là mệnh đề quan hệ rút gọn dạng bị động. Câu đầy đủ là 'all procedures which are written in this manual...'. Khi rút gọn, ta dùng quá khứ phân từ (V3/Ved). 'Written' là dạng V3 của 'write'. Dịch: Để tránh các vấn đề không mong muốn, tất cả các quy trình được viết trong sổ tay này phải được thực hiện.",
      en: "This is a reduced relative clause in the passive voice. The full sentence is 'all procedures which are written in this manual...'. When reduced, the past participle (V3/Ved) is used. 'Written' is the V3 form of 'write'. Translation: To avoid unexpected issues, all procedures written in this manual must be implemented.",
    },
    grammar_tags: ["participle", "reduced_relative_clause", "passive_voice"],
    vocab_tags: ["instructions", "manual"],
    difficulty: 4,
    distractor_notes: {
      B: "'Wrote' là động từ ở thì quá khứ đơn.",
      C: "'Writing' (V-ing) được dùng trong mệnh đề quan hệ rút gọn chủ động.",
      D: "'Write' là động từ nguyên thể.",
    },
    hint: "Are the procedures performing the action of writing, or are they being written?",
  },
  {
    id: "q18",
    question: "The word 'comprehensive' means...",
    options: [
      "expensive and luxurious",
      "difficult to understand",
      "including everything that is necessary",
      "happening over a large area",
    ],
    answer: "C",
    explanation: {
      vi: "'Comprehensive' (tính từ) có nghĩa là toàn diện, bao hàm đầy đủ. Dịch: 'bao gồm mọi thứ cần thiết'.",
      en: "'Comprehensive' (adjective) means complete and including everything that is necessary. Translation: 'including everything that is necessary'.",
    },
    grammar_tags: ["vocabulary"],
    vocab_tags: ["adjective", "description"],
    difficulty: 3,
    distractor_notes: {
      A: "Mô tả của 'opulent' hoặc 'lavish'.",
      B: "Mô tả của 'complicated' hoặc 'abstruse'.",
      D: "Mô tả của 'widespread'.",
    },
    hint: "Think of a comprehensive report or a comprehensive insurance plan.",
  },
  {
    id: "q19",
    question:
      "Customers will automatically receive a 10 percent discount on bulk items, ------ they make payment by Thursday.",
    options: ["while", "however", "if", "before"],
    answer: "C",
    explanation: {
      vi: "Câu này diễn tả một điều kiện. Việc nhận giảm giá (mệnh đề chính) phụ thuộc vào điều kiện thanh toán trước thứ Năm (mệnh đề phụ). 'If' (nếu) là liên từ chỉ điều kiện phù hợp. Dịch: Khách hàng sẽ tự động nhận được giảm giá 10% cho các mặt hàng số lượng lớn nếu họ thanh toán trước thứ Năm.",
      en: "This sentence expresses a condition. Receiving the discount (main clause) depends on the condition of paying by Thursday (subordinate clause). 'If' is the appropriate conditional conjunction. Translation: Customers will automatically receive a 10 percent discount on bulk items if they make payment by Thursday.",
    },
    grammar_tags: ["conjunction", "conditional"],
    vocab_tags: ["sales", "policy"],
    difficulty: 2,
    distractor_notes: {
      A: "'While' chỉ sự đồng thời hoặc tương phản.",
      B: "'However' là trạng từ liên kết, không phải liên từ phụ thuộc.",
      D: "'Before' chỉ thời gian.",
    },
    hint: "Receiving a discount depends on a certain action.",
  },
  {
    id: "q20",
    question:
      "Mr. Williams ------ that volunteers sign up to assist with the river cleanup by Friday.",
    options: ["requesting", "to be requested", "requests", "to request"],
    answer: "C",
    explanation: {
      vi: "Câu cần một động từ chính được chia theo chủ ngữ số ít 'Mr. Williams'. 'Requests' là động từ ở thì hiện tại đơn, ngôi thứ ba số ít. Dịch: Ông Williams yêu cầu các tình nguyện viên đăng ký hỗ trợ dọn dẹp sông trước thứ Sáu.",
      en: "The sentence needs a main verb conjugated for the singular subject 'Mr. Williams'. 'Requests' is the simple present, third-person singular form. Translation: Mr. Williams requests that volunteers sign up to assist with the river cleanup by Friday.",
    },
    grammar_tags: ["subject_verb_agreement", "verb_tense"],
    vocab_tags: ["communication", "community"],
    difficulty: 1,
    distractor_notes: {
      A: "'Requesting' là một hiện tại phân từ, không thể làm động từ chính một mình.",
      B: "'To be requested' là dạng bị động của động từ nguyên thể.",
      D: "'To request' là động từ nguyên thể.",
    },
    hint: "The sentence needs a main verb for the subject 'Mr. Williams'.",
  },
  {
    id: "q21",
    question:
      "Envelopes must be properly sealed ------ dropping them into the mailbox.",
    options: ["inside", "before", "beside", "while"],
    answer: "B",
    explanation: {
      vi: "Cần một từ nối chỉ trình tự thời gian. Hành động 'sealed' (niêm phong) phải xảy ra trước hành động 'dropping' (bỏ vào). 'Before' (trước khi) là lựa chọn đúng. Sau giới từ 'before' là một danh động từ (V-ing). Dịch: Phong bì phải được niêm phong đúng cách trước khi bỏ vào hòm thư.",
      en: "A word indicating time sequence is needed. The action of 'sealed' must happen before the action of 'dropping'. 'Before' is the correct choice. It is a preposition followed by a gerund (V-ing). Translation: Envelopes must be properly sealed before dropping them into the mailbox.",
    },
    grammar_tags: ["preposition", "gerund"],
    vocab_tags: ["instructions", "mail"],
    difficulty: 2,
    distractor_notes: {
      A: "'Inside' chỉ vị trí.",
      C: "'Beside' chỉ vị trí.",
      D: "'While' là liên từ, theo sau là mệnh đề S-V, không phải V-ing.",
    },
    hint: "What is the time relationship between sealing the envelope and putting it in the mailbox?",
  },
  {
    id: "q22",
    question:
      "------ the rugged mountain terrain, proper hiking footwear is recommended.",
    options: ["Due to", "Meanwhile", "In order that", "Even if"],
    answer: "A",
    explanation: {
      vi: "Cụm từ 'the rugged mountain terrain' là một cụm danh từ. 'Due to' (do, bởi vì) là một giới từ chỉ nguyên nhân, theo sau bởi một cụm danh từ. Dịch: Do địa hình núi gồ ghề, giày đi bộ đường dài phù hợp được khuyến nghị.",
      en: "The phrase 'the rugged mountain terrain' is a noun phrase. 'Due to' is a preposition of cause, which is followed by a noun phrase. Translation: Due to the rugged mountain terrain, proper hiking footwear is recommended.",
    },
    grammar_tags: ["preposition", "conjunction", "distinction"],
    vocab_tags: ["outdoors", "recommendation"],
    difficulty: 4,
    distractor_notes: {
      B: "'Meanwhile' là một trạng từ.",
      C: "'In order that' là một liên từ, theo sau là mệnh đề.",
      D: "'Even if' là một liên từ, theo sau là mệnh đề.",
    },
    hint: "The phrase after the blank is a noun phrase, not a full clause. The phrase explains the reason for the recommendation.",
  },
  {
    id: "q23",
    question:
      "The marketing initiative was quite unclear; ------, it was rejected.",
    options: ["however", "therefore", "moreover", "otherwise"],
    answer: "B",
    explanation: {
      vi: "Mệnh đề thứ hai là kết quả trực tiếp của mệnh đề thứ nhất. 'Therefore' (do đó, vì vậy) là trạng từ liên kết chỉ kết quả. Dịch: Sáng kiến tiếp thị khá không rõ ràng; do đó, nó đã bị từ chối.",
      en: "The second clause is a direct result of the first. 'Therefore' is a conjunctive adverb that indicates a result. Translation: The marketing initiative was quite unclear; therefore, it was rejected.",
    },
    grammar_tags: ["conjunctive_adverb", "cause_effect"],
    vocab_tags: ["business", "marketing", "planning"],
    difficulty: 3,
    distractor_notes: {
      A: "'However' chỉ sự tương phản.",
      C: "'Moreover' dùng để thêm thông tin.",
      D: "'Otherwise' chỉ một kết quả khác nếu điều kiện không được đáp ứng.",
    },
    hint: "The second part of the sentence is the logical result of the first part.",
  },
  {
    id: "q24",
    question:
      "The new application makes it easier for customers ------ their purchases.",
    options: ["tracking", "to track", "tracked", "to tracking"],
    answer: "B",
    explanation: {
      vi: "Cấu trúc 'make it + adj + for someone + to do something' (làm cho việc gì đó trở nên... cho ai đó). Sau tính từ 'easier' và 'for customers', ta cần một động từ nguyên thể có 'to' (to-infinitive). Dịch: Ứng dụng mới giúp khách hàng theo dõi việc mua hàng của họ dễ dàng hơn.",
      en: "The structure is 'make it + adj + for someone + to do something'. After the adjective 'easier' and 'for customers', a to-infinitive is required. Translation: The new application makes it easier for customers to track their purchases.",
    },
    grammar_tags: ["verb_form", "infinitive"],
    vocab_tags: ["technology", "e-commerce"],
    difficulty: 4,
    distractor_notes: {
      A: "Sai cấu trúc.",
      C: "Sai cấu trúc.",
      D: "Sai cấu trúc, 'to' không đi với V-ing trong trường hợp này.",
    },
    hint: "The structure is 'make it easy for someone to do something'.",
  },
  {
    id: "q25",
    question: "Choose the word that has the closest meaning to 'mandatory'.",
    options: ["optional", "compulsory", "advisory", "beneficial"],
    answer: "B",
    explanation: {
      vi: "'Mandatory' và 'compulsory' đều có nghĩa là bắt buộc.",
      en: "'Mandatory' and 'compulsory' both mean required by law or a rule; obligatory.",
    },
    grammar_tags: ["vocabulary", "synonym"],
    vocab_tags: ["rules", "policy"],
    difficulty: 3,
    distractor_notes: {
      A: "'Optional' là tự chọn, trái nghĩa với 'mandatory'.",
      C: "'Advisory' có nghĩa là tư vấn, cố vấn.",
      D: "'Beneficial' có nghĩa là có lợi.",
    },
    hint: "This word describes something you must do.",
  },
  {
    id: "q26",
    question:
      "If the company ------ the consultant's advice, the sales would have increased.",
    options: ["takes", "took", "had taken", "would take"],
    answer: "C",
    explanation: {
      vi: "Đây là câu điều kiện loại 3, diễn tả một giả định trái với quá khứ. Mệnh đề chính dùng 'would have + V3' (would have increased), vì vậy mệnh đề 'if' phải dùng thì quá khứ hoàn thành (had + V3). Dịch: Nếu công ty đã nghe theo lời khuyên của nhà tư vấn, doanh số đã tăng lên.",
      en: "This is a Type 3 conditional, expressing a hypothetical situation in the past. The main clause uses 'would have + V3' (would have increased), so the 'if' clause must use the past perfect tense (had + V3). Translation: If the company had taken the consultant's advice, the sales would have increased.",
    },
    grammar_tags: ["conditional", "type_3", "verb_tense"],
    vocab_tags: ["business", "finance"],
    difficulty: 4,
    distractor_notes: {
      A: "Sai thì, dùng cho câu điều kiện loại 1.",
      B: "Sai thì, dùng cho câu điều kiện loại 2.",
      D: "Sai cấu trúc.",
    },
    hint: "The main clause 'would have increased' points to a past unreal condition.",
  },
  {
    id: "q27",
    question:
      "Purchasing the entire program is less ------ than buying components separately.",
    options: ["cost", "costly", "costing", "costs"],
    answer: "B",
    explanation: {
      vi: "Sau động từ 'to be' (is) và trạng từ so sánh 'less', ta cần một tính từ. 'Costly' (tốn kém) là tính từ phù hợp. Dịch: Mua toàn bộ chương trình ít tốn kém hơn so với việc mua các thành phần riêng lẻ.",
      en: "After the verb 'to be' (is) and the comparative adverb 'less', an adjective is needed. 'Costly' is the correct adjective. Translation: Purchasing the entire program is less costly than buying components separately.",
    },
    grammar_tags: ["word_form", "adjective", "comparative"],
    vocab_tags: ["finance", "purchasing"],
    difficulty: 3,
    distractor_notes: {
      A: "'Cost' là danh từ hoặc động từ.",
      C: "'Costing' là hiện tại phân từ hoặc danh động từ.",
      D: "'Costs' là danh từ số nhiều hoặc động từ chia ở ngôi thứ 3 số ít.",
    },
    hint: "What kind of word follows 'is less...' to describe the subject?",
  },
  {
    id: "q28",
    question:
      "The representative for our group must have a high level of proficiency ------ English and Spanish.",
    options: ["with", "for", "in", "at"],
    answer: "C",
    explanation: {
      vi: "Cụm từ cố định là 'proficiency in something', có nghĩa là 'sự thành thạo về cái gì đó'. Dịch: Người đại diện cho nhóm của chúng ta phải có trình độ thành thạo cao về tiếng Anh và tiếng Tây Ban Nha.",
      en: "The fixed collocation is 'proficiency in something'. Translation: The representative for our group must have a high level of proficiency in English and Spanish.",
    },
    grammar_tags: ["preposition", "collocation"],
    vocab_tags: ["skills", "language"],
    difficulty: 3,
    distractor_notes: {
      A: "Sai giới từ.",
      B: "Sai giới từ.",
      D: "Sai giới từ.",
    },
    hint: "Which preposition is used with the noun 'proficiency'?",
  },
  {
    id: "q29",
    question: "By the time you receive this email, the package ------.",
    options: [
      "will ship",
      "has been shipped",
      "will have been shipped",
      "is shipping",
    ],
    answer: "C",
    explanation: {
      vi: "Cụm từ 'By the time + S + V(hiện tại)' là dấu hiệu của thì tương lai hoàn thành. Hành động 'ship' (giao hàng) sẽ hoàn tất trước một thời điểm trong tương lai (khi bạn nhận email). Câu mang nghĩa bị động (gói hàng được giao đi). Vì vậy, đáp án là thì tương lai hoàn thành bị động 'will have been shipped'. Dịch: Vào lúc bạn nhận được email này, gói hàng sẽ đã được gửi đi.",
      en: "The phrase 'By the time + S + V(present)' signals the future perfect tense. The action 'ship' will be completed before a future point in time (when you receive the email). The sentence is passive (the package is shipped). Therefore, the answer is the passive future perfect 'will have been shipped'. Translation: By the time you receive this email, the package will have been shipped.",
    },
    grammar_tags: ["verb_tense", "future_perfect", "passive_voice"],
    vocab_tags: ["shipping", "logistics"],
    difficulty: 5,
    distractor_notes: {
      A: "Sai thì và sai dạng (chủ động).",
      B: "Sai thì (hiện tại hoàn thành).",
      D: "Sai thì (hiện tại tiếp diễn).",
    },
    hint: "'By the time' indicates that one action will be completed before another future action.",
  },
  {
    id: "q30",
    question:
      "The personnel manager is reviewing applications to select the best ------ for the position.",
    options: ["qualify", "qualifying", "qualified", "to qualify"],
    answer: "B",
    explanation: {
      vi: "Câu này thiếu một danh từ chỉ người. Tuy nhiên, không có danh từ nào phù hợp trong các lựa chọn. 'Candidates' (ứng viên) là từ bị thiếu. 'Qualifying' có thể được sử dụng như một tính từ để bổ nghĩa cho danh từ đó (the best qualifying candidates). Trong trường hợp này, 'qualifying' được ngầm hiểu là 'ứng viên đủ điều kiện'. Dịch: Giám đốc nhân sự đang xem xét các đơn xin việc để chọn ra những ứng viên đủ điều kiện nhất cho vị trí này.",
      en: "This sentence is missing a noun for a person ('candidates'). 'Qualifying' can act as a participle adjective to modify that noun. In this context, 'qualifying' is understood to mean 'qualifying candidates'. Translation: The personnel manager is reviewing applications to select the best qualifying (candidates) for the position.",
    },
    grammar_tags: ["word_form", "participle", "adjective"],
    vocab_tags: ["recruitment", "human_resources"],
    difficulty: 5,
    distractor_notes: {
      A: "'Qualify' là động từ.",
      C: "'Qualified' là tính từ/quá khứ phân từ, thường dùng để mô tả người đã có đủ điều kiện (a qualified candidate).",
      D: "'To qualify' là động từ nguyên thể.",
    },
    hint: "The phrase 'the best...' needs a noun or an adjective modifying an implied noun.",
  },
  {
    id: "q31",
    question:
      "The company announced a list of suppliers ------ it considers to be the most reliable.",
    options: ["it", "itself", "they", "their"],
    answer: "A",
    explanation: {
      vi: "Trong mệnh đề 'it considers to be the most reliable', 'it' là chủ ngữ (the company) và 'considers' là động từ. Mệnh đề này bổ nghĩa cho 'suppliers'. Dịch: Công ty đã công bố danh sách các nhà cung cấp mà họ cho là đáng tin cậy nhất.",
      en: "In the clause 'it considers to be the most reliable', 'it' is the subject (the company) and 'considers' is the verb. This clause modifies 'suppliers'. Translation: The company announced a list of suppliers that it considers to be the most reliable.",
    },
    grammar_tags: ["pronoun", "relative_clause", "subject_pronoun"],
    vocab_tags: ["business", "supply_chain"],
    difficulty: 4,
    distractor_notes: {
      B: "'Itself' là đại từ phản thân.",
      C: "'They' sẽ không hợp lý vì 'company' là số ít.",
      D: "'Their' là tính từ sở hữu, cần một danh từ theo sau.",
    },
    hint: "The clause '... considers to be the most reliable' needs a subject. Who is doing the considering?",
  },
  {
    id: "q32",
    question: "The word 'lucrative' is best defined as:",
    options: [
      "producing a great deal of profit",
      "very complicated and detailed",
      "lasting for a very short time",
      "providing a useful service",
    ],
    answer: "A",
    explanation: {
      vi: "'Lucrative' là một tính từ có nghĩa là sinh lợi, có lãi. Dịch: 'tạo ra nhiều lợi nhuận'.",
      en: "'Lucrative' is an adjective that means producing a great deal of profit. Translation: 'producing a great deal of profit'.",
    },
    grammar_tags: ["vocabulary"],
    vocab_tags: ["finance", "business", "adjective"],
    difficulty: 4,
    distractor_notes: {
      B: "Định nghĩa của 'intricate' hoặc 'elaborate'.",
      C: "Định nghĩa của 'ephemeral' hoặc 'transient'.",
      D: "Định nghĩa của 'utilitarian'.",
    },
    hint: "This word is often used to describe a business, a contract, or a career.",
  },
  {
    id: "q33",
    question:
      "Regrettably, the company does not provide accommodations for temporary staff ------ working arrangement is less than 2 months.",
    options: ["who", "which", "whom", "whose"],
    answer: "D",
    explanation: {
      vi: "Cần một đại từ quan hệ để chỉ sự sở hữu. 'Whose' được dùng để nói 'sự sắp xếp công việc CỦA nhân viên tạm thời'. 'Whose working arrangement' có nghĩa là 'sự sắp xếp công việc của họ'. Dịch: Rất tiếc, công ty không cung cấp chỗ ở cho nhân viên tạm thời mà sự sắp xếp công việc của họ dưới 2 tháng.",
      en: "A relative pronoun indicating possession is needed. 'Whose' is used to say 'the working arrangement OF the temporary staff'. Translation: Regrettably, the company does not provide accommodations for temporary staff whose working arrangement is less than 2 months.",
    },
    grammar_tags: ["relative_clause", "possessive_pronoun"],
    vocab_tags: ["policy", "human_resources"],
    difficulty: 4,
    distractor_notes: {
      A: "'Who' làm chủ ngữ cho người.",
      B: "'Which' làm chủ ngữ/tân ngữ cho vật.",
      C: "'Whom' làm tân ngữ cho người.",
    },
    hint: "The pronoun needs to show possession: the arrangement belongs to the staff.",
  },
  {
    id: "q34",
    question:
      "The new law firm you are looking for is situated ------ the public library.",
    options: ["inside", "below", "beneath", "by"],
    answer: "D",
    explanation: {
      vi: "'By' là một giới từ có nghĩa là 'bên cạnh', 'gần'. Đây là lựa chọn hợp lý nhất trong các phương án. 'By', 'next to', và 'beside' có thể được dùng thay thế cho nhau. Dịch: Công ty luật mới mà bạn đang tìm kiếm nằm cạnh thư viện công cộng.",
      en: "'By' is a preposition meaning 'next to' or 'near'. It is the most logical choice among the options. 'By', 'next to', and 'beside' can be used interchangeably. Translation: The new law firm you are looking for is situated by the public library.",
    },
    grammar_tags: ["preposition", "preposition_of_place"],
    vocab_tags: ["locations", "directions"],
    difficulty: 3,
    distractor_notes: {
      A: "'Inside' có nghĩa là bên trong.",
      B: "'Below' có nghĩa là bên dưới (không tiếp xúc).",
      C: "'Beneath' có nghĩa là bên dưới.",
    },
    hint: "The sentence describes two buildings that are next to each other.",
  },
  {
    id: "q35",
    question:
      "Experts have recommended ------ the partnership between the two companies.",
    options: ["enhance", "enhancing", "to enhance", "enhancement"],
    answer: "B",
    explanation: {
      vi: "Sau động từ 'recommend', ta dùng danh động từ (V-ing). Dịch: Các chuyên gia đã đề xuất việc tăng cường quan hệ đối tác giữa hai công ty.",
      en: "The verb 'recommend' is followed by a gerund (V-ing). Translation: Experts have recommended enhancing the partnership between the two companies.",
    },
    grammar_tags: ["verb_form", "gerund"],
    vocab_tags: ["business", "partnership"],
    difficulty: 3,
    distractor_notes: {
      A: "'Enhance' là động từ nguyên thể.",
      C: "'To enhance' là động từ nguyên thể có 'to'.",
      D: "'Enhancement' là một danh từ.",
    },
    hint: "What verb form follows verbs like 'recommend', 'suggest', and 'consider'?",
  },
  {
    id: "q36",
    question:
      "------ the addition of over 200 spaces, the parking area is still full on weekends.",
    options: ["Despite", "Due to", "Besides", "Since"],
    answer: "A",
    explanation: {
      vi: "Câu diễn tả sự tương phản: có thêm chỗ đậu xe (tích cực) nhưng bãi đậu xe vẫn đầy (tiêu cực). 'Despite' (mặc dù) là một giới từ chỉ sự nhượng bộ, theo sau bởi một cụm danh từ ('the addition...'). Dịch: Mặc dù đã thêm hơn 200 chỗ, khu vực đậu xe vẫn đầy vào cuối tuần.",
      en: "The sentence expresses a contrast: more parking spaces were added (positive), but the lot is still full (negative). 'Despite' is a preposition of concession, followed by a noun phrase. Translation: Despite the addition of over 200 spaces, the parking area is still full on weekends.",
    },
    grammar_tags: ["preposition", "concession"],
    vocab_tags: ["city_life", "parking"],
    difficulty: 4,
    distractor_notes: {
      B: "'Due to' chỉ nguyên nhân.",
      C: "'Besides' có nghĩa là 'ngoài ra'.",
      D: "'Since' là liên từ chỉ nguyên nhân hoặc giới từ/liên từ chỉ thời gian.",
    },
    hint: "The sentence shows an unexpected result. The word you need is a preposition, not a conjunction.",
  },
  {
    id: "q37",
    question:
      "At Incheon Tower, we hold brainstorming sessions every month to help employees improve their ------ and productivity.",
    options: ["efficient", "efficiency", "efficiently", "efficiencies"],
    answer: "B",
    explanation: {
      vi: "Cần một danh từ song hành với danh từ 'productivity'. 'Efficiency' (sự hiệu quả, năng suất) là danh từ phù hợp. Dịch: Tại Tháp Incheon, chúng tôi tổ chức các buổi họp nhóm sáng tạo hàng tháng để giúp nhân viên cải thiện hiệu suất và năng suất làm việc.",
      en: "A noun is needed to be parallel with the noun 'productivity'. 'Efficiency' is the correct noun. Translation: At Incheon Tower, we hold brainstorming sessions every month to help employees improve their efficiency and productivity.",
    },
    grammar_tags: ["word_form", "noun", "parallel_structure"],
    vocab_tags: ["workplace", "performance"],
    difficulty: 2,
    distractor_notes: {
      A: "'Efficient' là tính từ.",
      C: "'Efficiently' là trạng từ.",
      D: "'Efficiencies' là danh từ số nhiều, nhưng 'efficiency' ở đây là một khái niệm không đếm được.",
    },
    hint: "The structure is 'improve their... and productivity'. You need a noun that is parallel to 'productivity'.",
  },
  {
    id: "q38",
    question:
      "The new intern is ------ young, he is highly skilled and reliable.",
    options: ["because", "so", "despite", "although"],
    answer: "D",
    explanation: {
      vi: "Câu diễn tả sự tương phản giữa tuổi tác và kỹ năng. 'Although' (mặc dù) là liên từ phụ thuộc dùng để nối hai mệnh đề có ý nghĩa tương phản. Dịch: Mặc dù thực tập sinh mới còn trẻ, anh ấy rất có tay nghề và đáng tin cậy.",
      en: "The sentence expresses a contrast between age and skill. 'Although' is a subordinating conjunction used to connect two contrasting clauses. Translation: Although the new intern is young, he is highly skilled and reliable.",
    },
    grammar_tags: ["conjunction", "concession"],
    vocab_tags: ["workplace", "skills"],
    difficulty: 2,
    distractor_notes: {
      A: "'Because' chỉ nguyên nhân.",
      B: "'So' chỉ kết quả.",
      C: "'Despite' là một giới từ, theo sau là danh từ/cụm danh từ.",
    },
    hint: "The sentence highlights an unexpected quality given the first piece of information.",
  },
  {
    id: "q39",
    question:
      "Choose the word that means 'to officially stop something for a period of time'.",
    options: ["resume", "initiate", "suspend", "terminate"],
    answer: "C",
    explanation: {
      vi: "'Suspend' là động từ có nghĩa là đình chỉ, tạm dừng một cái gì đó trong một khoảng thời gian.",
      en: "'Suspend' is a verb that means to officially stop something for a period of time.",
    },
    grammar_tags: ["vocabulary"],
    vocab_tags: ["business", "legal", "verb"],
    difficulty: 4,
    distractor_notes: {
      A: "'Resume' có nghĩa là bắt đầu lại.",
      B: "'Initiate' có nghĩa là khởi xướng, bắt đầu.",
      D: "'Terminate' có nghĩa là chấm dứt hoàn toàn.",
    },
    hint: "This word is often used for services, licenses, or memberships that are paused.",
  },
  {
    id: "q40",
    question:
      "The board of directors expects ------ the financial performance of the company.",
    options: ["improving", "to improve", "improve", "improved"],
    answer: "B",
    explanation: {
      vi: "Sau động từ 'expect', ta dùng động từ nguyên thể có 'to' (to-infinitive). Dịch: Ban giám đốc kỳ vọng sẽ cải thiện hiệu quả tài chính của công ty.",
      en: "The verb 'expect' is followed by a to-infinitive. Translation: The board of directors expects to improve the financial performance of the company.",
    },
    grammar_tags: ["verb_form", "infinitive"],
    vocab_tags: ["finance", "business"],
    difficulty: 2,
    distractor_notes: {
      A: "'Improving' là danh động từ.",
      C: "'Improve' là động từ nguyên thể không 'to'.",
      D: "'Improved' là quá khứ phân từ.",
    },
    hint: "What verb form follows 'expect', 'want', or 'plan'?",
  },
  {
    id: "q41",
    question:
      "Of all the truck models available, it can be difficult to figure out which would ------ suit your company’s needs.",
    options: ["well", "better", "best", "good"],
    answer: "C",
    explanation: {
      vi: "Cần một trạng từ để bổ nghĩa cho động từ 'suit'. Cụm từ 'Of all the truck models' cho thấy đây là phép so sánh nhất. 'Best' là dạng so sánh nhất của trạng từ 'well'. Dịch: Trong tất cả các mẫu xe tải hiện có, có thể khó để xác định mẫu nào sẽ phù hợp nhất với nhu cầu của công ty bạn.",
      en: "An adverb is needed to modify the verb 'suit'. The phrase 'Of all the truck models' indicates the superlative degree. 'Best' is the superlative form of the adverb 'well'. Translation: Of all the truck models available, it can be difficult to figure out which would best suit your company’s needs.",
    },
    grammar_tags: ["adverb", "superlative"],
    vocab_tags: ["business", "vehicles"],
    difficulty: 4,
    distractor_notes: {
      A: "'Well' là dạng nguyên mẫu.",
      B: "'Better' là dạng so sánh hơn.",
      D: "'Good' là tính từ.",
    },
    hint: "The comparison is being made among 'all the models'.",
  },
  {
    id: "q42",
    question:
      "The Web application that your team ------ last month earned top scores.",
    options: ["developing", "developed", "are developing", "will develop"],
    answer: "B",
    explanation: {
      vi: "Cụm từ 'last month' là dấu hiệu của thì quá khứ đơn. 'Developed' là dạng quá khứ đơn của động từ 'develop'. Dịch: Ứng dụng Web mà nhóm của bạn đã phát triển vào tháng trước đã đạt điểm cao nhất.",
      en: "The phrase 'last month' indicates the simple past tense. 'Developed' is the simple past form of the verb 'develop'. Translation: The Web application that your team developed last month earned top scores.",
    },
    grammar_tags: ["verb_tense", "simple_past"],
    vocab_tags: ["technology", "project_management"],
    difficulty: 1,
    distractor_notes: {
      A: "Đây là hiện tại phân từ.",
      C: "Sai thì (hiện tại tiếp diễn).",
      D: "Sai thì (tương lai đơn).",
    },
    hint: "The action happened and was completed 'last month'.",
  },
  {
    id: "q43",
    question:
      "The central terminal’s current ticketing counters will gradually be ------ by automatic machines.",
    options: ["replaced", "replacing", "to replace", "replace"],
    answer: "A",
    explanation: {
      vi: "Câu ở dạng bị động thì tương lai đơn, với cấu trúc 'will be + V3/Ved'. 'Replaced' là dạng V3/Ved của động từ 'replace'. Dịch: Các quầy bán vé hiện tại của nhà ga trung tâm sẽ dần được thay thế bằng máy tự động.",
      en: "The sentence is in the simple future passive voice, with the structure 'will be + V3/Ved'. 'Replaced' is the past participle form of 'replace'. Translation: The central terminal’s current ticketing counters will gradually be replaced by automatic machines.",
    },
    grammar_tags: ["passive_voice", "verb_tense", "future_simple"],
    vocab_tags: ["automation", "travel"],
    difficulty: 3,
    distractor_notes: {
      B: "Sai dạng, 'replacing' dùng cho thể chủ động hoặc tiếp diễn.",
      C: "Sai dạng.",
      D: "Sai dạng.",
    },
    hint: "Look at the structure 'will be...'. This indicates a passive form.",
  },
  {
    id: "q44",
    question:
      "We are committed to ------ our services to avoid complaints from customers.",
    options: ["improve", "improving", "improves", "improved"],
    answer: "B",
    explanation: {
      vi: "Cụm từ 'be committed to' là một trong những trường hợp đặc biệt mà giới từ 'to' đi với danh động từ (V-ing), không phải động từ nguyên thể. Dịch: Chúng tôi cam kết cải thiện dịch vụ của mình để tránh những phàn nàn từ khách hàng.",
      en: "The phrase 'be committed to' is a special case where the preposition 'to' is followed by a gerund (V-ing), not an infinitive. Translation: We are committed to improving our services to avoid complaints from customers.",
    },
    grammar_tags: ["verb_form", "gerund", "prepositional_phrase"],
    vocab_tags: ["customer_service", "commitment"],
    difficulty: 5,
    distractor_notes: {
      A: "Sai dạng, mặc dù 'to' thường đi với V-nguyên thể, đây là trường hợp ngoại lệ.",
      C: "Sai dạng.",
      D: "Sai dạng.",
    },
    hint: "The 'to' in 'committed to' is a preposition, not part of an infinitive.",
  },
  {
    id: "q45",
    question: "The city has plans ------ local parks by planting more trees.",
    options: ["revitalize", "revitalization", "to revitalize", "revitalizing"],
    answer: "C",
    explanation: {
      vi: "Danh từ 'plans' thường được theo sau bởi một động từ nguyên thể có 'to' (to-infinitive) để chỉ mục đích hoặc nội dung của kế hoạch. Dịch: Thành phố có kế hoạch hồi sinh các công viên địa phương bằng cách trồng thêm cây.",
      en: "The noun 'plans' is often followed by a to-infinitive to state the purpose or content of the plan. Translation: The city has plans to revitalize local parks by planting more trees.",
    },
    grammar_tags: ["verb_form", "infinitive"],
    vocab_tags: ["urban_planning", "environment"],
    difficulty: 3,
    distractor_notes: {
      A: "Sai dạng.",
      B: "'Revitalization' là danh từ, không phù hợp về cấu trúc.",
      D: "Sai dạng.",
    },
    hint: "How do you express the purpose of a plan?",
  },
  {
    id: "q46",
    question:
      "------ description of the jobs available is available on the website.",
    options: ["Detail", "Details", "A detailed", "Detailer"],
    answer: "C",
    explanation: {
      vi: "Cần một cụm danh từ làm chủ ngữ cho động từ 'is'. 'A detailed description' (một mô tả chi tiết) là cụm danh từ số ít phù hợp. 'Detailed' là một tính từ (quá khứ phân từ) bổ nghĩa cho danh từ 'description'. Dịch: Một mô tả chi tiết về các công việc hiện có sẵn trên trang web.",
      en: "A noun phrase is needed as the subject for the verb 'is'. 'A detailed description' is a suitable singular noun phrase. 'Detailed' is a participle adjective modifying the noun 'description'. Translation: A detailed description of the jobs available is available on the website.",
    },
    grammar_tags: ["word_form", "adjective", "noun", "subject_verb_agreement"],
    vocab_tags: ["recruitment", "job_search"],
    difficulty: 4,
    distractor_notes: {
      A: "Thiếu mạo từ và không phải là dạng tính từ bổ nghĩa.",
      B: "'Details' là danh từ số nhiều, không hợp với động từ 'is'.",
      D: "'Detailer' là danh từ chỉ người.",
    },
    hint: "The subject of the verb 'is' must be singular. You need a noun preceded by an adjective.",
  },
  {
    id: "q47",
    question: "What is the opposite of 'reluctant'?",
    options: ["hesitant", "eager", "uncertain", "compulsory"],
    answer: "B",
    explanation: {
      vi: "'Reluctant' có nghĩa là miễn cưỡng, không sẵn lòng. Từ trái nghĩa là 'eager', có nghĩa là háo hức, hăm hở.",
      en: "'Reluctant' means unwilling and hesitant. Its antonym is 'eager', which means keenly expectant or interested.",
    },
    grammar_tags: ["vocabulary", "antonym"],
    vocab_tags: ["adjective", "attitude"],
    difficulty: 3,
    distractor_notes: {
      A: "'Hesitant' (do dự) là từ đồng nghĩa với 'reluctant'.",
      C: "'Uncertain' (không chắc chắn) có nghĩa gần giống.",
      D: "'Compulsory' (bắt buộc) không liên quan.",
    },
    hint: "If you are not reluctant to do something, you are very willing and excited to do it.",
  },
  {
    id: "q48",
    question:
      "The employee handbook states the director is responsible for ------ administrative procedures.",
    options: ["to create", "created", "creating", "being created"],
    answer: "C",
    explanation: {
      vi: "Cấu trúc 'responsible for' được theo sau bởi một danh động từ (V-ing). Dịch: Sổ tay nhân viên nêu rõ giám đốc chịu trách nhiệm tạo ra các thủ tục hành chính.",
      en: "The structure 'responsible for' is followed by a gerund (V-ing). Translation: The employee handbook states the director is responsible for creating administrative procedures.",
    },
    grammar_tags: ["verb_form", "gerund", "preposition"],
    vocab_tags: ["responsibility", "policy", "management"],
    difficulty: 2,
    distractor_notes: {
      A: "Sai dạng.",
      B: "Sai dạng.",
      D: "Sai dạng bị động.",
    },
    hint: "The word 'for' is a preposition. What verb form follows a preposition?",
  },
  {
    id: "q49",
    question:
      "The company decided to ------ a new branch in Asia to expand its market presence.",
    options: ["establish", "establishment", "establishing", "established"],
    answer: "A",
    explanation: {
      vi: "Sau động từ 'decided to', ta cần một động từ nguyên thể không 'to'. Tuy nhiên, cấu trúc là 'decide to do something', vậy nên ta cần động từ nguyên thể 'establish'. Dịch: Công ty đã quyết định thành lập một chi nhánh mới ở châu Á để mở rộng sự hiện diện trên thị trường.",
      en: "The structure is 'decide to do something', so the base verb 'establish' is needed. Translation: The company decided to establish a new branch in Asia to expand its market presence.",
    },
    grammar_tags: ["verb_form", "infinitive"],
    vocab_tags: ["business", "expansion"],
    difficulty: 1,
    distractor_notes: {
      B: "'Establishment' là danh từ.",
      C: "'Establishing' là danh động từ/hiện tại phân từ.",
      D: "'Established' là quá khứ phân từ.",
    },
    hint: "After 'decided to...', you need a base verb.",
  },
  {
    id: "q50",
    question:
      "------ upgrading software, users must back up any important files.",
    options: ["Before", "Despite", "As soon as", "Along with"],
    answer: "A",
    explanation: {
      vi: "Câu diễn tả trình tự hành động: sao lưu file phải diễn ra trước khi nâng cấp phần mềm. 'Before' (trước khi) là một giới từ, theo sau là một danh động từ (V-ing), phù hợp với ngữ cảnh. Dịch: Trước khi nâng cấp phần mềm, người dùng phải sao lưu mọi tệp quan trọng.",
      en: "The sentence describes a sequence of actions: backing up files must happen before upgrading the software. 'Before' is a preposition followed by a gerund (V-ing), which fits the context. Translation: Before upgrading software, users must back up any important files.",
    },
    grammar_tags: ["preposition", "gerund", "sequence"],
    vocab_tags: ["technology", "instructions"],
    difficulty: 2,
    distractor_notes: {
      B: "'Despite' chỉ sự nhượng bộ.",
      C: "'As soon as' là liên từ, cần một mệnh đề theo sau.",
      D: "'Along with' có nghĩa là 'cùng với'.",
    },
    hint: "This is about the correct order of actions. The word you need can be followed by a V-ing form.",
  },
];
